/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package progetto.elementiGrafici;

import progetto.Controller.ControllerProiezione;
import progetto.Main;
import progetto.Session;
import progetto.functions.ValidatoreCampi;
import progetto.model.Proiezione;
import progetto.state.PrenotazionePostiState;

import javax.swing.*;
import javax.swing.border.LineBorder;
import java.awt.*;

/**
 *
 * @author francesco
 */
public class ProiezioneSingola extends javax.swing.JPanel {
    private Proiezione datiProiezione;
    /**
     * Creates new form ProiezioneSingola
     */
    public ProiezioneSingola(Proiezione proiezione) {
        this.datiProiezione = proiezione;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        prezzoField = new javax.swing.JTextField();

        jLabel1.setText("Data: "+ ValidatoreCampi.DATEFORMAT.format(datiProiezione.getData())+"     prezzo: ");
        prezzoField.setText(datiProiezione.getPrezzo());

        jLabel2.setText("Sala: "+datiProiezione.getIdSala()+"      posti disponibili: "+datiProiezione.getPostiLiberi());
        prezzoField.setEditable(false);

        if(Session.getSessioneCorrente().getUtenteLoggato().getTipo().equals("A")){
            jButton1.setText("Modifica");
            jButton1.addActionListener(evt ->{
                if(!prezzoField.isEditable()){
                    prezzoField.setEditable(true);
                    jButton1.setText("Salva");
                }else{
                    String tmp = prezzoField.getText();
                    if(ValidatoreCampi.isNumeric(tmp)){
                        datiProiezione.setPrezzo(tmp);
                        new ControllerProiezione().modifyProiezione(datiProiezione);
                        prezzoField.setEditable(false);
                        jButton1.setText("Modifica");
                        prezzoField.setBorder( new JTextField().getBorder());
                    }else{
                        prezzoField.setBorder( new LineBorder(Color.red,2));
                    }
                }
            });


        }else{
            jButton1.setText("Prenota");
            jButton1.addActionListener(evt -> {
                Session.getSessioneCorrente().setIdRiferimentoProiezione(datiProiezione.getId());
                new PrenotazionePostiState().doAction(Main.context);
            });
            prezzoField.setBorder(null);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prezzoField,javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10,10,10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(prezzoField)
                            .addComponent(jLabel2)
                            .addComponent(jButton1)
                            )
                        .addGap(10, 10, 10))
                    )
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;

    private javax.swing.JTextField prezzoField;
    // End of variables declaration//GEN-END:variables
}
