/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package progetto.view;

import progetto.Main;
import progetto.Session;
import progetto.state.*;

import javax.swing.*;

/**
 *
 * @author franc
 */
public class GUI extends javax.swing.JFrame {
    //private static JFrame frame ;
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        this.getContentPane().removeAll();
        //JPanel n = new Login();

        //this.getContentPane().add(n);
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);


        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    public void showMenu(){
        jMenuBar1 = new javax.swing.JMenuBar();
        profiloMenu = new javax.swing.JMenuItem();
        jMenuLogout = new javax.swing.JMenuItem();

        filmMenu = new javax.swing.JMenuItem();
        filmMenu.setText("Film");
        filmMenu.addActionListener(evt -> new FilmState().doAction(Main.context));
        jMenuBar1.add(filmMenu);

        if (Session.getSessioneCorrente().getUtenteLoggato().getTipo().equals("U")){
            prenotazioniMenu = new javax.swing.JMenuItem();
            prenotazioniMenu.setText("Prenotazioni"); //visibile solo per gli utenti
            prenotazioniMenu.addActionListener(evt-> new PrenotazioniState().doAction(Main.context));

            jMenuBar1.add(prenotazioniMenu);
        }

        if (Session.getSessioneCorrente().getUtenteLoggato().getTipo().equals("D")){
            gestioneBigliettiMenu = new javax.swing.JMenuItem();
            gestioneBigliettiMenu.setText("Gestione Biglietti"); //visibile solo per i dipendenti
            gestioneBigliettiMenu.addActionListener(evt-> new PrenotazioniState().doAction(Main.context));
            accettazioneBiglietti = new javax.swing.JMenuItem();
            accettazioneBiglietti.setText("Accettazione biglietti"); //visibile solo per i dipendenti
            accettazioneBiglietti.addActionListener(evt-> new AccettazioneBigliettiState().doAction(Main.context));
            jMenuBar1.add(gestioneBigliettiMenu);
            jMenuBar1.add(accettazioneBiglietti);
        }

        if (Session.getSessioneCorrente().getUtenteLoggato().getTipo().equals("A")){
            visualizzaVendite = new javax.swing.JMenuItem();
            visualizzaDipendenti = new javax.swing.JMenuItem();
            inserisciFilm = new javax.swing.JMenuItem();
            visualizzaVendite.setText("Visualizza vendite");
            visualizzaVendite.addActionListener(evt -> new VisualizzaVenditeState().doAction(Main.context));

            jMenuBar1.add(visualizzaVendite);

            visualizzaDipendenti.setText("Visualizza dipendenti");
            visualizzaDipendenti.addActionListener(evt -> new GestioneDipendentiState().doAction(Main.context));



            jMenuBar1.add(visualizzaDipendenti);

            inserisciFilm.setText("Inserimento Film");
            inserisciFilm.addActionListener(evt -> new InserimentoFilmState().doAction(Main.context));
            jMenuBar1.add(inserisciFilm);
            //jMenuBar1.add(amministrazioneMenu);
        }


        profiloMenu.setText("Profilo");
        profiloMenu.addActionListener(evt -> new VisualizzaDatiState().doAction(Main.context));


        jMenuBar1.add(profiloMenu);

        jMenuLogout.setText("Logout");
        jMenuLogout.addActionListener(evt -> {
            Main.frame.hideMenu();
            Session.getSessioneCorrente().logOut();
            new LoginState().doAction(Main.context);
        });
        jMenuBar1.add(jMenuLogout);
        jMenuBar1.setVisible(true);
        setJMenuBar(jMenuBar1);

    }

    public void hideMenu(){
        jMenuBar1 = null;
        this.setJMenuBar(null);
    }
    public void aggiornaPannello(JPanel n){
        this.getContentPane().removeAll();
        this.add(n);
        this.setResizable(false);
        this.pack();
        this.getContentPane().requestFocusInWindow();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem filmMenu;
    private javax.swing.JMenuItem prenotazioniMenu;
    private javax.swing.JMenuItem profiloMenu;
    private javax.swing.JMenuItem gestioneBigliettiMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem visualizzaVendite;
    private javax.swing.JMenuItem visualizzaDipendenti;
    private javax.swing.JMenuItem jMenuLogout;
    private javax.swing.JMenuItem inserisciFilm;
    private javax.swing.JMenuItem accettazioneBiglietti;


    // End of variables declaration//GEN-END:variables
}
