/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package progetto.view;

import progetto.Controller.ControllerPrenotazione;
import progetto.Controller.ControllerProiezione;
import progetto.Main;
import progetto.Session;
import progetto.functions.TraduttoreMatrice;
import progetto.functions.TrasformatoreArrayList;
import progetto.model.Prenotazione;
import progetto.model.Proiezione;
import progetto.state.FilmState;
import progetto.state.ProiezioneState;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;

/**
 *
 * @author francesco
 */
public class GestionePrenotazioneUtente extends javax.swing.JPanel {
    private ArrayList postiSelezionati = new ArrayList();
    private String imgPath = "progetto/elementiGrafici/poltrona.jpg";
    private Color selezionato = new Color(0,125,0);
    private ImageIcon icon  ;
    /**
     * Creates new form postiCinema
     */
    public GestionePrenotazioneUtente() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {


        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        String proizioneId = Session.getSessioneCorrente().getIdRiferimentoProiezione();
        int posti[][] = new ControllerProiezione().getProezioneByID(proizioneId).getPostiAttualiOccupati();

        int righe = posti.length;
        int colonne = posti[0].length;
        icon = new ImageIcon(imgPath);
        Image image = icon.getImage();
        int lunghezza = 770/(righe);
        int altezza =  357/(colonne);

        Image newIcon;
        if(lunghezza < altezza){
            newIcon = image.getScaledInstance(lunghezza, lunghezza,  java.awt.Image.SCALE_SMOOTH);
        }else{
            newIcon = image.getScaledInstance(altezza, altezza,  java.awt.Image.SCALE_SMOOTH);
        }

        icon = new ImageIcon(newIcon);
        jPanel1 = new javax.swing.JPanel(new GridLayout(righe,colonne));
        //JPanel posti = new JPanel(new GridLayout(righe,colonne));
        JButton tmp ;

        for(int x=0; x<righe;x++){
            for(int y=0;y<colonne;y++){
                tmp = new JButton();
                tmp.setIcon(icon);
                if(posti[x][y] == 0){
                    tmp.setVisible(false);
                }else if (posti[x][y] == 2){
                    tmp.setBackground(Color.RED);
                    tmp.setEnabled(false);
                    tmp.setToolTipText("Posto occupato");
                }else{
                    tmp.setVisible(true);
                    tmp.setName(x+":"+y);
                    tmp.setToolTipText("Seleziona");
                    tmp.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {

                            JButton source = (JButton) evt.getSource();
                            if(source.getBackground()!=selezionato){
                                String name = source.getName();
                                postiSelezionati.add(name+";");
                                int numbers[][] = TraduttoreMatrice.stringToMatrice(name) ;
                                posti[numbers[0][0]][numbers[0][1]] = 2;


                                source.setBackground(selezionato);
                                source.setToolTipText("Annulla selezione");
                            }else{
                                String name = source.getName();
                                postiSelezionati.remove(name+";");
                                int numbers[][] = TraduttoreMatrice.stringToMatrice(name) ;
                                posti[numbers[0][0]][numbers[0][1]] = 1;
                                source.setBackground(null);
                                source.setToolTipText("Seleziona");
                            }

                        }
                    });
                }
                jPanel1.add(tmp);
            }
        }

        jButton1.setText("Prenota");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if(postiSelezionati.size()>0){
                    //System.out.println(TrasformatoreArrayList.arrayListToStringMat(postiSelezionati));
                    //idGeneratore, idProiezione, idFilm, postoAssegnato
                    String prenotazione = Session.getSessioneCorrente().getUtenteLoggato().getId()
                            + "," + Session.getSessioneCorrente().getIdRiferimentoProiezione()
                            + "," + Session.getSessioneCorrente().getIdRiferimentoFilm()
                            + "," + TrasformatoreArrayList.arrayListToStringMat(postiSelezionati);
                    new ControllerPrenotazione().insertPrenotazione(prenotazione);

                    Proiezione modified = new ControllerProiezione().getProezioneByID(Session.getSessioneCorrente().getIdRiferimentoProiezione());
                    modified.setPostiAttualiOccupati(posti);
                    modified.setPostiLiberi(modified.getPostiLiberi()-postiSelezionati.size());
                    new ControllerProiezione().modifyProiezione(modified);


                    JOptionPane.showMessageDialog(null, "Prenotazione effettuata con sucesso!\n Verrai reindirizzato al catalogo film");
                    new FilmState().doAction(Main.context);
                }

            }
        });

        jButton2.setText("Indietro");
        jButton2.setToolTipText("Ritorna alle proiezioni");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new ProiezioneState().doAction(Main.context);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
