/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package progetto.view;

import progetto.Main;
import progetto.Session;
import progetto.state.Context;
import progetto.state.LoginState;

import javax.swing.*;
import javax.swing.event.MenuEvent;
import javax.swing.event.MenuListener;

/**
 *
 * @author franc
 */
public class GUI extends javax.swing.JFrame {
    //private static JFrame frame ;
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        this.getContentPane().removeAll();
        //JPanel n = new Login();

        //this.getContentPane().add(n);
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);


        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    public void showMenu(){
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuLogout = new javax.swing.JMenu();





        jMenu1 = new javax.swing.JMenu();
        jMenu1.setText("Film");
        jMenuBar1.add(jMenu1);

        if (Session.getSessioneCorrente().getUtenteLoggato().getTipoUtente().equals("U")){
            jMenu2 = new javax.swing.JMenu();
            jMenu2.setText("Prenotazioni"); //visibile solo per gli utenti
            jMenuBar1.add(jMenu2);
        }

        if (Session.getSessioneCorrente().getUtenteLoggato().getTipoUtente().equals("D")){
            jMenu4 = new javax.swing.JMenu();
            jMenu4.setText("Gestione Biglietti"); //visibile solo per i dipendenti
            jMenuBar1.add(jMenu4);
        }

        if (Session.getSessioneCorrente().getUtenteLoggato().getTipoUtente().equals("A")){
            jMenu5 = new javax.swing.JMenu();
            jMenuItem3 = new javax.swing.JMenuItem();
            jMenuItem4 = new javax.swing.JMenuItem();
            jMenu5.setText("Amministrazione"); //visibile solo admin
            jMenuItem3.setText("Visualizza vendite");
            jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jMenuItem3ActionPerformed(evt);
                    }
                });

            jMenu5.add(jMenuItem3);

            jMenuItem4.setText("Visualizza dipendenti");
            jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jMenuItem4ActionPerformed(evt);
                    }
                });
            
            jMenu5.add(jMenuItem4);
            jMenuBar1.add(jMenu5);
        }


        jMenu3.setText("Profilo");
        jMenuBar1.add(jMenu3);

        jMenuLogout.setText("Logout");
        jMenuLogout.addMenuListener(new MenuListener() {
            @Override
            public void menuSelected(MenuEvent e) {
                Main.frame.hideMenu();
                Session.getSessioneCorrente().logOut();
                new LoginState().doAction(Main.context);
            }

            @Override
            public void menuDeselected(MenuEvent e) {

            }

            @Override
            public void menuCanceled(MenuEvent e) {

            }
        });
        jMenuBar1.add(jMenuLogout);
        jMenuBar1.setVisible(true);
        setJMenuBar(jMenuBar1);

    }

    public void hideMenu(){
        jMenuBar1 = null;
        this.setJMenuBar(null);
    }
    public void aggiornaPannello(JPanel n){
        this.getContentPane().removeAll();
        this.add(n);
        this.pack();
        this.setResizable(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenu jMenuLogout;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
