/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
*/
package progetto.view;

import progetto.Controller.ControllerPrenotazione;
import progetto.Session;
import progetto.elementiGrafici.PrenotazioneSingola;
import progetto.elementiGrafici.ProiezioneSingola;
import progetto.model.Prenotazione;
import progetto.model.Proiezione;

import javax.swing.*;
import java.util.Collection;
import java.util.Date;
import java.util.Iterator;

/**
 *
 * @author franc
 */
public class VisualizzaPrenotazioni extends javax.swing.JPanel {

    /**
     * Creates new form VisualizzaPrenotazioni
     */
    public VisualizzaPrenotazioni() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel prenotazioni = new JPanel();
        prenotazioni.setLayout(new BoxLayout(prenotazioni, BoxLayout.Y_AXIS));

        Collection<Prenotazione> listaPrenotazioni = new ControllerPrenotazione().getByIDGeneratoreAfterDate(Session.getSessioneCorrente().getUtenteLoggato().getId(), new Date());
        Prenotazione tmpPrenotazione;
        for (Iterator<Prenotazione> iterator = listaPrenotazioni.iterator(); iterator.hasNext(); ){

            tmpPrenotazione = iterator.next();
            JPanel j = new PrenotazioneSingola(tmpPrenotazione);
            prenotazioni.add(j);
            j.setOpaque(false);
        }
        jScrollPane1 = new javax.swing.JScrollPane(prenotazioni);
        jScrollPane1.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
