/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package progetto.elementiGrafici;


import progetto.Controller.ControllerPrenotazione;
import progetto.Controller.ControllerProiezione;
import progetto.Main;
import progetto.Session;
import progetto.model.Film;
import progetto.model.Prenotazione;
import progetto.model.Proiezione;
import progetto.state.FilmState;
import progetto.state.PrenotazioneDipendeteState;
import progetto.state.ProiezioneState;

import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collection;

/**
 *
 * @author francesco
 */
public class FilmSingolo extends javax.swing.JPanel {
    private Film datiFilm;
    ImageIcon logoFilm ;
    private final String imagePath = "src/main/java/progetto/elementiGrafici/";
    /**
     * Creates new form FilmSingolo
     */
    public FilmSingolo(Film datiFilm) {
        BufferedImage img = null;
        this.datiFilm= datiFilm;
        try {
            img = ImageIO.read(new File(imagePath + datiFilm.getLocandina().trim()));
        } catch (IOException e) {
        }
        this.logoFilm = new ImageIcon(img);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeDescrizioneFilm = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();



        nomeDescrizioneFilm.setText("<html> <h2>"+datiFilm.getNome()+"</h2><br />  "+datiFilm.getInfo()+"</html>");


        jLabel2.setIcon(logoFilm);

        if(Main.context.getState() instanceof FilmState){
            jButton1.setText("Proiezioni");
        }else{
            jButton1.setText("Biglietti");
        }

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if(Main.context.getState() instanceof FilmState){
                    Session.getSessioneCorrente().setIdRiferimentoFilm(datiFilm.getId());
                    new ProiezioneState().doAction(Main.context);
                }else{
                    Session.getSessioneCorrente().setIdRiferimentoFilm(datiFilm.getId());
                    new PrenotazioneDipendeteState().doAction(Main.context);
                }


            }
        });
        if(Session.getSessioneCorrente().getUtenteLoggato().getTipo().equals("A")){
            bottoneModifica = new javax.swing.JButton();
            bottoneModifica.setText("Elimina");
            bottoneModifica.addActionListener(evt->{
                Collection<Proiezione> proiezioniDaEliminare = new ControllerProiezione().getProiezioneByIDFilm(datiFilm.getId());
                Collection<String> ids = proiezioniDaEliminare.stream().map(Proiezione::getId).collect(ArrayList::new,ArrayList::add,ArrayList::addAll);
                ids.stream().forEach(x-> new ControllerProiezione().deleteProiezione(x));

                Collection<Prenotazione> prenotazioniDaEliminare = new ControllerPrenotazione().getPrenotazioniByIDFilm(datiFilm.getId());
                ids = prenotazioniDaEliminare.stream().map(Prenotazione::getId).collect(ArrayList::new,ArrayList::add,ArrayList::addAll);
                ids.stream().forEach(x-> new ControllerProiezione().deleteProiezione(x));

                new FilmState().doAction(Main.context);
            });

            componeteVariabile = bottoneModifica;
        }else{
            jLabel3 = new javax.swing.JLabel();
            jLabel3.setText("prezzo: "+datiFilm.getPrezzo()+"€");
            componeteVariabile = jLabel3;
        }


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nomeDescrizioneFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(componeteVariabile, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                           .addComponent(nomeDescrizioneFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(20,20,20)
                        .addComponent(componeteVariabile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    )
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel nomeDescrizioneFilm;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;

    private javax.swing.JButton bottoneModifica;
    private javax.swing.JComponent componeteVariabile;
    // End of variables declaration//GEN-END:variables
}
